/*
-- Query: SELECT * FROM localidades
LIMIT 0, 1000

-- Date: 2023-04-29 11:51
*/
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (1,'LA ESCONDIDA',4);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (2,'KILOMETRO 548',4);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (3,'COLONIA EL CACIQUE LLORON',4);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (4,'LEGUA 41',4);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (5,'LAS CHACRAS',6);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (6,'LOS CADILLOS',6);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (7,'VILLA QUILINO',6);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (8,'QUILINO',6);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (9,'CARRENLEUFU',5);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (10,'LAGO BLANCO',5);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (11,'VILLA SANTOS TESEI',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (12,'HURLINGHAM',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (13,'WILLIAM C. MORRIS',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (14,'ORATORIO MORANTE',21);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (15,'GODOY',21);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (16,'CAMPO LA VICTORIA',21);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (17,'VILLA MERCEDES',19);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (18,'LA RIVERA',19);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (19,'DIQUE VULPIANI',19);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (20,'LA RIBERA',19);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (21,'SAN FRANCISCO DE ALFARCITO',10);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (22,'SANTA ANA DE LA PUNA',10);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (23,'TUSAQUILLAS',10);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (24,'SANTA ANA',10);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (25,'TRANCAS',10);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (26,'RINCONADILLAS',10);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (27,'SALADO',10);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (28,'ABDON CASTRO TOLAY',10);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (29,'SANTUARIO DE TRES POZOS',10);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (30,'TOLARITO',10);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (31,'28 DE JULIO',5);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (32,'NAUPA HUEN',16);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (33,'CHILCA JULIANA',22);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (34,'EL MANZANO',13);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (35,'LAS CHACRAS',13);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (36,'MALARGUE',13);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (37,'LA JUNTA',13);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (38,'LUANCO',13);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (39,'LAS LENAS',13);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (40,'EL CHACAY',13);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (41,'AGUA ESCONDIDA',13);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (42,'MINACAR',13);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (43,'EL INFIERNILLO',13);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (44,'LOS CARRIZALES',13);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (45,'EL VATRO',13);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (46,'RINCON CHICO',13);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (47,'LA SALINILLA',13);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (48,'EL ALAMBRADO',13);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (49,'CALMUCO',13);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (50,'LLANO BLANCO',13);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (51,'PATA MORA',13);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (52,'RIO GRANDE',13);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (53,'LOS CORRALES',13);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (54,'EL CARAPACHO',13);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (55,'LA VALENCIANA',13);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (56,'LOS MOLLES',13);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (57,'MOGOTES ASPEROS',6);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (58,'OJO DE AGUA',6);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (59,'ESTANCIA DE GUADALUPE',6);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (60,'SAN FELIPE',6);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (61,'TRES LOMAS',6);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (62,'LA ARGENTINA',6);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (63,'CORREA',21);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (64,'BERRETTA',21);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (65,'ESTACION BERRETA',21);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (66,'EL CHALTEN',20);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (67,'EL ARBOLITO',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (68,'LOS BARRILES',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (69,'COLONIA LA PERLA',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (70,'SARASA',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (71,'PEARSON',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (72,'COLON',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (73,'KILOMETRO 404',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (74,'VILLA CACIQUE',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (75,'EL SAUCE',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (76,'BARKER',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (77,'BENITO JUAREZ',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (78,'CORONEL RODOLFO BUNGE',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (79,'LOPEZ',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (80,'SAN ANTONIO',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (81,'EL LUCHADOR',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (82,'LA TINTA',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (83,'TEDIN URIBURU',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (84,'LOS CONQUISTADORES',8);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (85,'GANCEDO',4);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (86,'LA BOLSA',4);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (87,'LABORDE',6);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (88,'GENERAL GALARZA',8);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (89,'MOJOTORO',17);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (90,'ISLAS DE VAQUEROS',17);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (91,'SANTA GERTRUDIS',17);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (92,'LA CALDERILLA',17);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (93,'LOS SAUCES',17);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (94,'LOS PORONGOS',17);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (95,'LA CALDERA',17);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (96,'EL GALLINATO',17);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (97,'CAMPO ALEGRE',17);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (98,'LA FALDA DE SAN ANTONIO',3);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (99,'EL HUECO',3);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (100,'LA TERCENA',3);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (101,'LA CARRERA',3);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (102,'POMANCILLO',3);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (103,'VILLA LAS PIRQUITAS',3);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (104,'COLLAGASTA',3);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (105,'SAN JOSE',3);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (106,'POMANCILLO OESTE',3);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (107,'POMANCILLO ESTE',3);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (108,'SAN ANTONIO',3);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (109,'CRUCE MUNOZ',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (110,'VILLA ALFREDO FORTABAT',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (111,'CUARTEL II  AEROPUERTO',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (112,'ESPIGAS',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (113,'RECALDE',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (114,'CAMPO ELSSIRY',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (115,'EL PORVENIR',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (116,'SIERRAS BAYAS',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (117,'OLAVARRIA',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (118,'CHACRAS DE PIBUEL',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (119,'VIRGEN DE LA LOMA',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (120,'SAN PEDRO',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (121,'CALERA AVELLANEDA',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (122,'EL MIRADOR',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (123,'SAN QUILCO',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (124,'COLONIA SAN MIGUEL',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (125,'SIERRA CHICA',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (126,'LAS PIEDRITAS',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (127,'VILLA LA SERRANIA',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (128,'ITURREGUI',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (129,'VILLA MONICA',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (130,'BLANCAGRANDE',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (131,'CERRO SOTUYO',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (132,'COLONIA HINOJO',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (133,'MAPIS',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (134,'CAMPO BELGRANO',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (135,'VILLA ARRIETA',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (136,'BLANCA CHICA',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (137,'SAN GREGORIO',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (138,'ROCHA',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (139,'HINOJO',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (140,'COLONIA NIEVAS',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (141,'LA PARDA',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (142,'SAN JACINTO',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (143,'LA PROVIDENCIA',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (144,'SANTA LUISA',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (145,'POURTALE',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (146,'LA MODERNA',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (147,'SAN ANTONIO',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (148,'LA CARMELITA',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (149,'LOS CHILENOS',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (150,'CAMPO STRIEBECK',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (151,'COLONIA ITURRASPE',21);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (152,'COLONIA LA POSTA',21);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (153,'AREQUITO',21);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (154,'SAN JOSE DE AGUILAR',17);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (155,'PUCALLPA',17);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (156,'LIZOITE',17);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (157,'LA SOLEDAD',17);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (158,'HORNILLOS',17);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (159,'EL PUESTO',17);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (160,'LA FALDA',17);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (161,'RODEO PAMPA',17);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (162,'PUCARA',17);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (163,'LA HUERTA',17);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (164,'CAMPO LA PAZ',17);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (165,'PUEBLO VIEJO',17);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (166,'SAN FRANCISCO',17);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (167,'SAN JOSE',17);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (168,'ABRA DE SANTA CRUZ',17);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (169,'SANTA CRUZ',17);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (170,'CHORRO',17);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (171,'SANTA VICTORIA',17);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (172,'ABRA DE SAN ANTONIO',17);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (173,'ANTIGAL',17);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (174,'LAGUNA',17);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (175,'SAN FELIPE',17);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (176,'SANTA CRUZ DE AGUILAR',17);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (177,'MECOYITA',17);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (178,'ACOYTE',17);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (179,'RIO PIEDRAS',17);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (180,'LUMBRERAS',17);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (181,'ARENALES',17);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (182,'SAN RAMIREZ',8);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (183,'LIHUEL CALEL',11);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (184,'PUELCHES',11);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (185,'GENERAL LAGOS',21);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (186,'PAMPA LA PORTENA',4);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (187,'CORZUELA NORTE',4);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (188,'SAN ANTONIO',4);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (189,'COLONIA JUAN LAVALLE',4);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (190,'PAMPA ZAPPA',4);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (191,'COLONIA SAN LORENZO',4);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (192,'CAMPO CANTON',4);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (193,'PAMPA ALSINA',4);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (194,'CORZUELA',4);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (195,'LA CIENAGA',19);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (196,'LAS AGUADAS',19);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (197,'TALA VERDE',19);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (198,'EL PUESTO',19);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (199,'LOS MOLLES',19);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (200,'CANADON SECO',20);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (201,'LA ESCALERA',12);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (202,'LA TORRECITA',12);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (203,'HUACO',12);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (204,'VILLA SANAGASTA',12);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (205,'ADROGUE',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (206,'JOSE MARMOL',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (207,'SAN JOSE',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (208,'RAFAEL CALZADA',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (209,'CLAYPOLE',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (210,'MINISTRO RIVADAVIA',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (211,'BURZACO',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (212,'MALVINAS ARGENTINAS',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (213,'GLEW',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (214,'LONGCHAMPS',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (215,'DON ORIONE',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (216,'SAN FRANCISCO SOLANO',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (217,'BELL VILLE',6);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (218,'COLONIA COMPIANI',6);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (219,'CALETA OLIVIA',20);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (220,'NUEVA VIZCAYA',8);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (221,'TORTUGUITAS',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (222,'DEL VISO',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (223,'JOSE C. PAZ',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (224,'GARZA',22);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (225,'LA VIGIA',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (226,'LA VUELTA',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (227,'ROBERTO CANO',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (228,'SANTA FELISA',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (229,'LA SOLEDAD',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (230,'LA CALDERA',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (231,'LOS INDIOS',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (232,'LA CONCEPCION',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (233,'LA ROJERA',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (234,'LA BEBA',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (235,'BARRIO LAS MARGARITAS',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (236,'LAS CARABELAS',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (237,'LAS POLVAREDAS',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (238,'LA VUELTA CHICA',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (239,'HUNTER',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (240,'VILLA MANUEL POMAR',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (241,'LA TIGRA',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (242,'ROJAS',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (243,'ESTACION SOL DE MAYO',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (244,'RAFAEL OBLIGADO',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (245,'VILLA PARQUE CECIR',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (246,'LA VERDE',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (247,'SAN BASILIO',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (248,'VILLA GENERAL MITRE',22);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (249,'SAN ROQUE',6);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (250,'CERRO PELADO',6);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (251,'AMBOY',6);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (252,'FLORIDA NEGRA',20);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (253,'BELLA VISTA',20);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (254,'EL SALADO',20);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (255,'SUARDI',21);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (256,'COLONIA SAN JOSE',10);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (257,'ALONSO',10);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (258,'VOLCAN DE YACORAITE',10);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (259,'YACORAITE',10);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (260,'HUACALERA',10);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (261,'LA TOMA',19);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (262,'MAQUINCHAO',16);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (263,'CALLE ANGOSTA',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (264,'NEWTON',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (265,'SAN MARTIN',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (266,'CHAS',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (267,'GENERAL BELGRANO',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (268,'LA VERDE',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (269,'GORCHS',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (270,'EL DESCANSO',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (271,'COLONIA EL SALADO',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (272,'LAVALLE',7);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (273,'PUERTO VIEJO',7);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (274,'LA LOMA',7);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (275,'RINCON DE SANTA LUCIA',7);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (276,'RINCON DE SOTO',7);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (277,'ENRIQUE URIEN',4);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (278,'LA VIRUELA',4);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (279,'LA MANUELA',4);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (280,'LA CARLOTA',4);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (281,'CAMPO COLLA',21);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (282,'LAS HIGUERITAS',21);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (283,'CORONEL RODRIGUEZ',21);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (284,'SANTA CLARA DE BUENA VISTA',21);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (285,'EL MOJON',6);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (286,'EL GUANACO',6);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (287,'LA MAZA',6);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (288,'SANTA CATALINA',6);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (289,'LA PIEDRA BLANCA',6);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (290,'AGUA DE ORO',6);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (291,'POZO DE MOLINA',6);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (292,'POZO DEL SIMBOL',6);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (293,'EL JORDAN',6);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (294,'LA BARRANCA',6);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (295,'POZO DE LAS OLLAS',6);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (296,'PUNTA DEL MONTE',6);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (297,'LA VICTORIA',6);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (298,'SAN MIGUEL',6);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (299,'ALTO DE FIERRO',6);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (300,'SANTA ISABEL',6);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (301,'LA PENCA',6);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (302,'SAN ANTONIO',6);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (303,'LA VICTORIA OESTE',6);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (304,'CAMPO GRANDE',6);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (305,'LA VICTORIA E',6);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (306,'3 DE MAYO',14);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (307,'GARUHAPE',14);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (308,'SAN MIGUEL',14);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (309,'PUERTO GARUHAPE',14);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (310,'SALSACATE',6);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (311,'VILLA VISO',6);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (312,'CASA BLANCA',6);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (313,'TANINGA',6);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (314,'PUEBLO VIEJO',6);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (315,'SAN EUSEBIO',6);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (316,'LAS LAGUNITAS',6);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (317,'LA TIGRA',6);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (318,'COLONIA LA VERDE',6);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (319,'COLONIA MARCOS SASTRE',6);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (320,'CAMPO LOS CORRALITOS',6);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (321,'COLONIA EL DORADO',6);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (322,'CAMPO LOS ALGARROBOS',6);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (323,'COLONIA LA CONCORDIA',6);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (324,'SAN MELITON',6);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (325,'CAYUQUEO',6);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (326,'CAMPO COSTA',6);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (327,'COLONIA LA UNION',6);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (328,'LA HERRADURA',6);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (329,'SAN SEVERO',6);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (330,'CAMPO SANTA RITA',6);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (331,'COLONIA 10 DE MAYO',6);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (332,'COLONIA EL BALQUIN',6);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (333,'COLONIA EL PIQUILLIN',6);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (334,'COLONIA CORRAL DEL BAJO',6);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (335,'CAMPO LAS CHACRAS',6);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (336,'CUATRO CAMINOS',6);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (337,'POTRO MUERTO',6);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (338,'EL UCLE',6);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (339,'CORRAL DEL BAJO',6);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (340,'CAMPO VIONNET',6);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (341,'COLONIA PICO CHACO',6);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (342,'RAMON J. CARCANO',6);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (343,'COLONIA LA LOLA',6);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (344,'COLONIA LA CELINA',6);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (345,'COLONIA EL DESCANSO',6);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (346,'CNIA NORTE',6);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (347,'COLONIA ESPERANZA',6);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (348,'COLONIA CORRAL DE GUARDIA',6);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (349,'CAMPO SANTA ELENA',6);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (350,'COLONIA LA LEONCITA',6);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (351,'CAMPO SAN ELIAS',6);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (352,'CAMPO LA LUISITA',6);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (353,'CAMPO LOS GALGOS',6);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (354,'CAMPO CRESPOP BALLESTERS',6);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (355,'CAMPO YANZI',6);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (356,'COLONIA SANTA RITA',6);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (357,'LUCA',6);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (358,'ENRIQUE CARBO',8);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (359,'ALARCON',8);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (360,'GENERAL RACEDO',8);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (361,'CARCEL',10);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (362,'PUNTA CORRAL',10);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (363,'COIRURO',10);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (364,'AGUA BENDITA',10);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (365,'TUMBAYA',10);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (366,'TUMBAYA GRANDE',10);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (367,'LEONES',6);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (368,'EL PALMAR',4);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (369,'GUEMES',4);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (370,'LA ARMONIA',4);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (371,'EL QUEBRACHO',4);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (372,'LOTE 126',4);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (373,'EL DESCANSO',4);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (374,'LA GRINGA',4);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (375,'LOS CIENAGOS',4);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (376,'4 DE FEBRERO',4);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (377,'LOS PEREYRAS',4);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (378,'TORRE DEL MIRADOR',4);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (379,'MONTE CASEROS',4);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (380,'POZO EL ZAPALLAR',4);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (381,'EL MOJO',4);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (382,'CRUCE PENALOZA',4);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (383,'LAS MARGARITAS',4);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (384,'ROSALES',4);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (385,'CENTRAL NORTE',4);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (386,'POZO DE LA PAVA',4);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (387,'LAS CUATRO BOCAS',4);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (388,'EL MILAGRO',4);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (389,'LOS PLACERES',4);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (390,'POZO DE LA MULA',4);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (391,'MANANTIALES',4);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (392,'LA ESMERALDA',4);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (393,'POZO DEL NEGRO',4);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (394,'BALBUENA',4);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (395,'MIRAFLORES',4);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (396,'EL RETIRO',4);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (397,'CAMPO LA CHINA',4);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (398,'LA MEDIA LUNA',4);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (399,'1 DE MAYO',4);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (400,'PASO DE LA CRUZ',4);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (401,'LOTE 76',4);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (402,'SANTA VICTORIA',4);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (403,'PALO MARCADO',4);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (404,'TECHAT',4);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (405,'LOTE 71',4);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (406,'LAS PUERTAS',4);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (407,'POZO LA GRINGA',4);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (408,'EL CANON',4);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (409,'LAS HACHERAS',4);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (410,'LOS QUIRQUINCHOS',4);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (411,'YAPEYU',4);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (412,'LA CHEOGUE',4);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (413,'NUEVA UNION',4);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (414,'BAJADA ALTA',4);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (415,'EL ALGARROBO',4);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (416,'BAJO HONDO',4);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (417,'EL QUEBRACHO BALEADO',4);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (418,'SAN LORENZO',4);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (419,'LOS ROSALES',4);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (420,'LAS CHACRAS',6);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (421,'EL VERGEL',6);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (422,'ESTACION COLONIA TIROLESA',6);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (423,'EL QUEBRACHAL',6);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (424,'COLONIA LOS ALGARROBOS',6);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (425,'LA CORINA',6);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (426,'COLONIA RIO CHICO',6);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (427,'COLONIA TIROLESA',6);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (428,'SANTA ELENA',6);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (429,'LA PUERTA',6);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (430,'LAS AVISPAS',21);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (431,'LABORDEBOY',21);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (432,'GENERAL GELLY',21);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (433,'CAMPO FONDATO',21);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (434,'CAMPO GHIANO',21);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (435,'CAMPO ULLA',21);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (436,'EL TREBOL',21);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (437,'CAMPO RIBERI',21);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (438,'POTRERILLOS',17);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (439,'EL JARDIN',17);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (440,'LOZADA',6);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (441,'SALSIPUEDES',6);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (442,'LA ESTANCITA',6);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (443,'EL PUEBLITO',6);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (444,'LA JAULA',13);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (445,'CAPIZ',13);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (446,'SAN CARLOS',13);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (447,'PAREDITAS',13);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (448,'CHILECITO',13);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (449,'EL PARRAL',13);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (450,'PIEDRAS BLANCAS',13);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (451,'TRES ESQUINAS',13);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (452,'LA CONSULTA',13);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (453,'BARRIO EL CEPILLO',13);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (454,'PASO DE LAS CARRETAS',13);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (455,'EUGENIO BUSTOS',13);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (456,'EL CAPACHO',13);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (457,'BARRIO CARRASCO',13);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (458,'LOS ALAMITOS',13);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (459,'VILLA EL CHACON',13);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (460,'CAMPAMENTO VILLEGAS',5);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (461,'SANTA TERESA',21);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (462,'FRANCISCO PAZ',21);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (463,'CHACHARRAMENDI',11);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (464,'VALLE DAZA',11);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (465,'BARRIO CHIVILCOY',13);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (466,'EL DIVISADERO',13);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (467,'BUEN ORDEN',13);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (468,'MONTECASEROS',13);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (469,'BARRIO LA ESTACION',13);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (470,'CHAPANAY',13);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (471,'BARRIO NTRA. SRA. DE FATIMA',13);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (472,'TRES PORTENAS',13);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (473,'CHIVILCOY',13);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (474,'BARRIO LOS CHARABONES',13);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (475,'ALTO VERDE',13);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (476,'CIUDAD DE SAN MARTIN',13);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (477,'EL RAMBLON',13);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (478,'BARRIO EMANUEL',13);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (479,'VILLA CENTENARIO',13);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (480,'EL ESPINO',13);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (481,'PALMIRA',13);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (482,'NUEVA CALIFORNIA',13);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (483,'TRES ESQUINAS',13);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (484,'ALTO SALVADOR',13);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (485,'COLONIA LAMBARE',13);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (486,'EL RINCON',5);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (487,'EL BLANCO',5);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (488,'EL CAJON',5);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (489,'CHOLILA',5);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (490,'VILLA LAGO RIVADAVIA',5);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (491,'LA PUERTA',6);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (492,'PINTOS',6);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (493,'EL ROSARIO',6);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (494,'LA CUMBRE',6);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (495,'VILLA TERCERA',24);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (496,'EX INGENIO LOS RALOS',24);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (497,'LAS MERCEDES',24);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (498,'VILLA RECASTE',24);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (499,'CAMPO LA FLOR',24);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (500,'RUTA 5 KM 132',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (501,'SUIPACHA',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (502,'GENERAL RIVAS',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (503,'LOS CARDALES',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (504,'CUARTEL VIII',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (505,'ESTACION LA NEGRA',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (506,'LA DULCE',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (507,'CUARTEL IX',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (508,'CUARTEL IV',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (509,'FORTIN ARENALES',21);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (510,'CAMPO BONAZOLA',21);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (511,'LAS TAPERITAS',21);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (512,'LANTERI',21);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (513,'CAMPO SIETE PROVINCIAS',21);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (514,'FLOR DE ORO',21);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (515,'LA BRITANICA',21);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (516,'DIVISADERO',17);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (517,'YACOCHUYA',17);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (518,'EL PASO',17);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (519,'LAS CONCHAS',17);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (520,'CAFAYATE',17);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (521,'SANTA BARBARA',17);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (522,'TOLOMBOM',17);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (523,'OJEDA',11);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (524,'ALTA ITALIA',11);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (525,'CAMPO GALLO',22);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (526,'CAITA TORO',16);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (527,'CHANQUIN',16);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (528,'SAN ANTONIO',9);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (529,'ISLA OCA',9);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (530,'COLONIA FORMOSA',9);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (531,'LA COLONIA',9);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (532,'FORMOSA',9);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (533,'GARRIDO',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (534,'LAVALLE',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (535,'EL EDEN',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (536,'LA LOMA',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (537,'PIERES',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (538,'EL MORO',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (539,'LA GUITARRA',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (540,'NAPALEOFU',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (541,'LA ALIANZA',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (542,'SANTA MARIA',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (543,'EL PAMPERO',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (544,'PUERTA DEL DIABLO',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (545,'LA FLORESTA',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (546,'ARENAS VERDES',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (547,'LA MALACARA',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (548,'SAN PASCUAL',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (549,'DOS NACIONES',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (550,'SAN MANUEL',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (551,'LA PROVIDENCIA',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (552,'LAS TOSCAS',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (553,'LAS NUTRIAS',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (554,'LAHORE',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (555,'TOME Y TRAIGA',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (556,'LOBERIA',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (557,'EL LENGUARAZ',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (558,'LA BODEGA',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (559,'TAMANGUEYU',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (560,'LICENCIADO MATIENZO',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (561,'SAN ANTONIO',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (562,'MOROMAR',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (563,'ALTO EL BOLSON',3);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (564,'LAS CUEVAS',3);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (565,'CORRAL BLANCO',3);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (566,'LAGUNA BLANCA',3);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (567,'BARRANCA LARGA',3);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (568,'VILLA VIL',3);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (569,'SAN IGNACIO LOTEO VELEZ CRESPO',6);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (570,'SANTA MONICA',6);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (571,'SANTA ROSA DE CALAMUCHITA',6);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (572,'ARROYO SECO',6);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (573,'CAMPANA MAHUIDA',16);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (574,'ARROYO LOS BERROS',16);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (575,'LAS HERAS',20);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (576,'COLONIA LA SARITA',8);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (577,'RINCON LUCAS SUD',8);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (578,'VISTA ALEGRE NORTE',15);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (579,'VISTA ALEGRE SUR',15);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (580,'BARRIO RUCA LUHE',15);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (581,'MUYO',24);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (582,'ALPACHIRI',24);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (583,'LAS LENGUAS',24);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (584,'EL MOLINO',24);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (585,'COCHUNA',24);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (586,'LA CALERA',24);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (587,'LAS PAVAS',24);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (588,'POSTA CAMBIO ZALAZAR',9);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (589,'PASO FLORES',16);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (590,'EL SOMBRERO',7);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (591,'LA MARTA',7);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (592,'SAN GREGORIO',7);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (593,'SAN ISIDRO',7);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (594,'PASO SAN JUAN',7);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (595,'PASO LOS ANGELES',7);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (596,'ISLA TALAR',7);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (597,'LA CUCUCHA',7);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (598,'BUENA ESPERANZA',7);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (599,'STELLA MARIS',7);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (600,'SAN MARTIN',7);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (601,'EL QUEBRACHO',7);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (602,'ESTANCIA SANTA RITA',7);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (603,'CAMPO MORATO',7);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (604,'SAN ANTONIO',7);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (605,'RINCON DEL PAGO',7);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (606,'INVERNADA',7);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (607,'PAGO DE LOS DESEOS',7);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (608,'COLONIA 3 DE ABRIL',7);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (609,'EL ESPINILLO',4);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (610,'AGUAS BLANCAS',17);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (611,'COLONIA TERESA',21);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (612,'CUBANEA',16);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (613,'CHIPAUQUIL',16);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (614,'PILO LIL',15);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (615,'GUANACOS',15);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (616,'LOS CHANARITOS',6);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (617,'DONA LUISA',22);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (618,'SABAGASTA',22);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (619,'NUEVA POMPEYA',4);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (620,'ALDEA APELEG',5);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (621,'CAMPO PIAGGIO',21);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (622,'LAPACHITO',4);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (623,'COLONIAS UNIDAS',4);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (624,'LOS TALARES',6);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (625,'LA RANCHERITA',6);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (626,'COLONIA CAROLINA',7);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (627,'COLONIA ISABEL VICTORIA',7);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (628,'VILLA OLIVARI',7);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (629,'COLONIA PANDO',7);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (630,'COLONIA PEREIRA',8);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (631,'COLONIA SAN ANSELMO',8);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (632,'MOLINO DOLL',8);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (633,'COLONIA OFICIAL 16',8);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (634,'COLONIA AYMAN',8);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (635,'BANDERITAS',8);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (636,'COLONIA LA BERTA',8);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (637,'COLONIA SAN LORENZO',8);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (638,'COLONIA LA MARTA',8);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (639,'DIEGO LOPEZ',8);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (640,'COLONIA LA LATA',8);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (641,'COLONIA SANTA LUCIA',8);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (642,'COLONIA OFICIAL 18',8);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (643,'LAS MULITAS',8);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (644,'ARROYO SEPULTURA',8);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (645,'ARROYO LAS LECHIGUANAS',8);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (646,'PASTOR BRITOS',8);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (647,'RINCON DEL GATO',8);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (648,'PERDICES',8);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (649,'DISTRITO PERDICES',8);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (650,'NANCAY',8);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (651,'LA PROVIDENCIA',8);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (652,'COLONIA EL SAUCESITO',8);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (653,'CRUCESITAS',8);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (654,'ORO VERDE',8);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (655,'ARROYO CORRALITO',8);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (656,'ALDEA SANTA ROSA',8);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (657,'ARROYO GRANDE',8);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (658,'COLONIA OFICIAL NÂ° 5',8);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (659,'COLONIA SAN MARTIN',8);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (660,'ESTANCIA LA SILVIA',8);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (661,'COLONIA SAGASTUME',8);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (662,'COLONIA SAN RAMON',8);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (663,'SAN CIPRIANO',8);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (664,'LAS ACHIRAS',8);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (665,'LOS CEIBOS',8);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (666,'DISTRITO CHILCAS',8);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (667,'DISTRITO HINOJAL',8);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (668,'RINCON DEL DOLL',8);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (669,'MONTOYA',8);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (670,'COLONIA ADIVINOS',8);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (671,'EL CHAJARI',8);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (672,'PICHI MAHUIDA',16);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (673,'MINA 3',20);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (674,'MAUA',21);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (675,'LA POTASA',21);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (676,'DOS ROSAS Y LA LEGUA',21);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (677,'LA DARSENA',22);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (678,'SAN RAMON',22);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (679,'EL ZANJON',22);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (680,'VILLA MATOQUE',22);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (681,'GUAMPACHA',22);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (682,'VILLA GUASAYAN',22);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (683,'POZO DEL TOBA',22);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (684,'QUEBRACHO COTO',22);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (685,'VILLA ROBLES',22);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (686,'SIMOCA',24);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (687,'SOLDADO MALDONADO',24);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (688,'LOS PEREYRA NORTE',24);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (689,'SOL DE MAYO',22);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (690,'JUANILLO',22);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (691,'PUNTA POZO',22);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (692,'EL AIBE',22);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (693,'ABRA GRANDE',22);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (694,'REMES',22);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (695,'SAN BENITO',22);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (696,'EL DEAN',22);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (697,'SAN VICENTE',22);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (698,'SANTA CATALINA',22);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (699,'SANTA MARIA',22);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (700,'CASPI CORRAL',22);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (701,'VACA HUANUNA',22);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (702,'CANAL MELERO',22);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (703,'LA SIMONA',22);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (704,'LA NENA',22);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (705,'TRES CRUCES',22);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (706,'YUCHAN',22);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (707,'LA NORIA',22);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (708,'SAUCE SOLO',22);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (709,'AMAMA',22);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (710,'VILLA BRANA',22);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (711,'LIBERTAD',22);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (712,'NEGRA MUERTA',22);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (713,'KM 49',22);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (714,'CAMPO GRANDE',22);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (715,'VILLA MERCEDES',22);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (716,'SANTO DOMINGO',22);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (717,'AMICHA',22);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (718,'LEZCANOS',22);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (719,'LOS OVEJEROS',22);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (720,'SOTELOS',22);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (721,'LOS ROMANOS',22);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (722,'VILLA HIPOLITA',22);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (723,'VACA HUMAN',22);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (724,'TIO POZO',22);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (725,'VILLA NUEVA',22);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (726,'HUACHANA',22);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (727,'SUMAMAO',22);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (728,'AHI VEREMOS',22);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (729,'POZO DEL ARBOLITO',22);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (730,'COLONIA PUENTE DEL GUALEG',8);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (731,'COLONIA LAS PEPAS',8);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (732,'COLONIA SANTA ROSA',8);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (733,'SAN MIGUEL',8);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (734,'COLONIA NUEVA SAN MIGUEL',8);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (735,'ROLDAN',22);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (736,'SAN ANTONIO',22);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (737,'PUNTA DEL MONTE',8);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (738,'EL HOYON',22);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (739,'POZO AZUL',14);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (740,'NUESTRA SENORA DE ITATI',14);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (741,'DURAN',14);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (742,'TRES VECINOS',14);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (743,'FORESTAL SAN ANTONIO',14);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (744,'DISTRITO TALA',8);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (745,'LAGO MELIQUINA',15);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (746,'AHI VEREMOS',22);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (747,'EL SAUZAL',22);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (748,'COLONIA ABORIGEN CHACO',4);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (749,'COLONIA ABORIGEN',4);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (750,'ATOJ POZO',22);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (751,'VUELTA DE LA BARRANCA',22);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (752,'COLONIA REFFINO',8);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (753,'ESTACION YUQUERI',8);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (754,'LOMA LIMPIA',8);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (755,'EL GATO',8);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (756,'COLONIA OFICIAL N 13',8);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (757,'GONZALEZ CALDERON',8);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (758,'LAS TOSCAS',8);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (759,'CRUCESITAS TERCERA',8);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (760,'DISTRITO COSTA URUGUAY SUR',8);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (761,'MONTE REDONDO',8);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (762,'LAS TUNAS',8);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (763,'SAUCE SUD',8);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (764,'LOS CAJONES',19);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (765,'LAS BARRANCAS',19);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (766,'LAS ISLITAS',19);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (767,'SANTA ANA',19);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (768,'BALDE DE ESCUDERO',19);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (769,'LAS PALOMAS',19);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (770,'COLONIA CECILIO ECHEVERRIA',7);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (771,'CAZADORES CORRENTINOS',7);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (772,'LAS GRUTAS',16);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (773,'CAMPO HARDY',21);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (774,'LOS TABANOS',21);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (775,'EL CRUCERO',22);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (776,'SALTO ENCANTADO',14);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (777,'ALGARROBAL',7);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (778,'CERNA',7);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (779,'COSTA SANTA LUCIA',7);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (780,'9 DE JULIO',7);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (781,'COLONIA JUAN RAMON VIDAL',7);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (782,'ARROYO VENTANA',16);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (783,'CANADA SECA',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (784,'SAN GENARO',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (785,'LOS LAURELES',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (786,'MASSEY',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (787,'ESTANCIA EL MERIDIANO',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (788,'GENERAL VILLEGAS',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (789,'COLONIA LA BELITA',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (790,'LA JOSEFA',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (791,'GONDRA',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (792,'VILLA CICLON',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (793,'MOORES',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (794,'CAMPOS FRIA',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (795,'PICHINCHA',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (796,'DRABBLE',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (797,'EL RECAO',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (798,'SAN JOSE',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (799,'ESCUELA AGRARIA',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (800,'FORTIN REPUBLICA',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (801,'LA MARGARITA',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (802,'ESTACION MILLACO',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (803,'VILLA SABOYA',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (804,'EL DIA',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (805,'CUARTEL II',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (806,'CORONEL CHARLONE',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (807,'PIEDRITAS',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (808,'VILLA SAUZE',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (809,'LA CATALINA',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (810,'SANTA ELEODORA',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (811,'TAMBEROS UNIDOS',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (812,'LOS ANGELES',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (813,'EMILIO V. BUNGE',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (814,'BANDERALO',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (815,'VOLTA',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (816,'CAMPESINOS UNIDOS',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (817,'SANTA REGINA',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (818,'LA TRADICION',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (819,'CANNING',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (820,'LUIS GUILLON',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (821,'9 DE ABRIL',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (822,'MONTE GRANDE',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (823,'EL JAGUEL',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (824,'VILLA HUIDOBRO',6);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (825,'LA JUANITA',8);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (826,'LA JAULA',8);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (827,'COLONIA ENSAYO',8);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (828,'LOS CERRILLOS',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (829,'FUNKE',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (830,'SAN MIGUEL DEL MONTE',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (831,'LA ELINA',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (832,'SAN GENARO',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (833,'ABBOTT',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (834,'SANTA MARIA',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (835,'EL ROSARIO',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (836,'EL SIASGO',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (837,'ZENON VIDELA DORNA',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (838,'GOYENECHE',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (839,'SAN MARCELO',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (840,'EL DORADO',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (841,'LA COSTA',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (842,'MAHON',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (843,'SANTO DOMINGO',21);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (844,'TRES CAPONES',14);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (845,'LAS TUNAS',14);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (846,'COLONIA SANTA ELOISA',8);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (847,'VILLA DEL ROSARIO',8);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (848,'MANFREDI',6);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (849,'LAS TINAJAS',22);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (850,'ARAUCO',12);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (851,'AIMOGASTA',12);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (852,'UDPINANGO',12);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (853,'LA CAUCHITA',12);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (854,'TINOCAN',12);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (855,'LA CIMBRITA',12);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (856,'TERMAS DE SANTA TERESITA',12);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (857,'SAN ANTONIO',12);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (858,'ESTACION MAZAN',12);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (859,'VILLA MAZAN',12);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (860,'BANADO DE LOS PANTANOS',12);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (861,'MACHIGASTA',12);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (862,'LA CANCHITA',12);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (863,'CUESTA BLANCA',6);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (864,'TRES LOMAS',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (865,'EL PANTANOSO',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (866,'SAN SILVERIO',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (867,'LOS CARDOS',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (868,'BALCARCE',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (869,'LA SARA',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (870,'EL GLIPTODONTE',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (871,'TRES ESQUINAS',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (872,'ALELUYA',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (873,'BOSCH',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (874,'COLONIA BALCARCE',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (875,'SAN SIMON',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (876,'BELLA VISTA',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (877,'EL CAPRICHO',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (878,'JUAN VICENTY',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (879,'EL VOLCAN',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (880,'ESQ DE LAHITTE',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (881,'CUARTEL III',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (882,'LOS PINOS',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (883,'RAMOS OTERO',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (884,'LA ESPERANZA',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (885,'CINCO CERROS',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (886,'EL PARQUE',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (887,'LA PALOMA',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (888,'ESTACION LA ALBORADA',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (889,'LLANOS',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (890,'SAN AGUSTIN',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (891,'CABANA SAN JUAN',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (892,'LA DELIA',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (893,'NAPALEOFU',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (894,'VILLA LAGUNA LA BRAVA',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (895,'SAN ALBERTO',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (896,'EL VIGILANTE',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (897,'EL CERRO',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (898,'EL VERANO',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (899,'LA ADELA',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (900,'PUERTA DEL ABRA',1);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (901,'DEAN FUNES',6);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (902,'VILLA DEL PRADO',6);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (903,'CAVANAGH',6);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (904,'GASTONA',24);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (905,'FINCA LEON CORNET',24);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (906,'GASTONILLA',24);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (907,'LA HIGUERA',24);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (908,'LAS FALDAS',24);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (909,'FINCA LA FALDA',24);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (910,'ARCADIA',24);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (911,'CAVIA CUE',7);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (912,'COSTA CHICA',7);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (913,'TRES CRUCES',7);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (914,'MEDIO',7);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (915,'EMPEDRADO LIMPIO',7);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (916,'INDIO MUERTO',7);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (917,'COSTA GRANDE',7);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (918,'LAGUNITA',7);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (919,'ESPINALLAR',7);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (920,'PASO LOVERA',7);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (921,'ALBARDONES',7);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (922,'RAMONES',7);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (923,'ORATORIO',7);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (924,'SANTOS LUGARES',7);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (925,'ARROYO PONTON',7);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (926,'CAMPO GRANDE',7);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (927,'AGUIRRE CUE',7);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (928,'LOMAS DE GALARZA',7);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (929,'EL POLLO',7);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (930,'PEICHOTO CUE',7);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (931,'MALOYAS',7);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (932,'CHANAR',7);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (933,'ESQUIVEL CUE',7);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (934,'CERRUDO CUE',7);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (935,'COLONIA LLANO',7);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (936,'SAN LUIS DEL PALMAR',7);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (937,'TACUARAL',7);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (938,'COLONIA EL SIMBOLAR',22);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (939,'CAMPO LA UNION',21);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (940,'LOS CARDOS',21);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (941,'BARDA DEL MEDIO',16);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (942,'CONTRALMIRANTE CORDERO',16);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (943,'SANTA MARIA NORTE',21);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (944,'BUENA VISTA',6);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (945,'SAN GERONIMO',6);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (946,'PALACIOS',21);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (947,'EL BRETE',17);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (948,'EL TALA',17);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (949,'LOS MOGOTES',17);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (950,'SENILLOSA',15);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (951,'AGUADA TOLEDO',15);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (952,'ARROYITO',15);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (953,'CHINA MUERTA',15);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (954,'LAS PENAS',6);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (955,'LOS ROBLES',24);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (956,'SAN JOSE DE FLORES',24);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (957,'LA CIENAGA',24);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (958,'RINCON DE BALDERRAMA',24);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (959,'ACHERAL',24);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (960,'ALTO DE LEIVA',24);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (961,'ALDEA SAN JUAN',8);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (962,'CAMPO SCARAFIOCCA',6);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (963,'COLONIA GARZON',6);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (964,'CAMPO EL CHILO',6);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (965,'CAMPO FIORETTA',6);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (966,'CAPILLA GARZON',6);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (967,'CAMPO PEROTTI',6);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (968,'COLONIA LOLA',6);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (969,'CAMPO CAPRIVI',6);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (970,'LAS PETACAS',6);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (971,'CAMPO LAS SELVAS',6);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (972,'CAMPO SAN ALFREDO',6);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (973,'CAMPO MACAGNO',6);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (974,'CAMPO ROSSI',6);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (975,'CAMPO BERTOGLIO',6);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (976,'CUESTA DEL RIO',6);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (977,'COLONIA BELLA VISTA',6);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (978,'CAMPO NIGRO SUR',6);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (979,'CAMPO JANON',6);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (980,'CAMPO NIGRO NORTE',6);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (981,'CAMPO LA ROSA',6);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (982,'COLONIA SANTA CATALINA',6);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (983,'CAMPO DEL BEL',6);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (984,'CAMPO MARENGO',6);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (985,'PUENTE LAS SELVAS',6);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (986,'COLONIA LOS TAMARINDOS',6);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (987,'CAMPO BOAGLIO',6);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (988,'CAMPO BATTISTON',6);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (989,'MONIGOTES',21);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (990,'SIERRITA SAN JOS',14);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (991,'TARANCO',14);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (992,'SAN JOSE',14);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (993,'COLONIA SAN JOSE',14);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (994,'PINDAPOY',14);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (995,'MONTE GRANDE',7);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (996,'SAN ANTONIO',7);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (997,'PUERTO TALA',7);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (998,'SAN ESTEBAN',6);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (999,'POTRILLO OSCURO',11);
INSERT INTO `` (`ID_Localidad`,`Localidad`,`ID_Provincia`) VALUES (1000,'BARRANCAS COLORADAS',11);
