/*
-- Query: SELECT * FROM Productos
LIMIT 0, 1000

-- Date: 2023-04-29 11:52
*/
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (1,'AMSTEL LATA ',1,114.22,217.02,170,1);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (2,'BLUE MOON LATA ',1,167.15,317.59,137,1);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (3,'BLUEMOON PORRON ',1,138.38,262.92,0,1);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (4,'BUDWEISER ',1,110.00,209.00,0,1);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (5,'GROLSCH BARRIL ',1,9237.03,17550.36,0,1);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (6,'GROLSCH LATA ',1,87.08,165.45,0,1);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (7,'GROLSCH PORRON ',1,138.38,262.92,0,1);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (8,'HEINEKEN BARRIL ',1,2510.55,4770.05,0,1);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (9,'HEINEKEN LATA ',1,109.36,207.78,84,1);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (10,'HEINEKEN ',1,67.59,128.42,0,1);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (11,'HEINEKEN PORRON ',1,60.14,114.27,0,1);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (12,'IMPERIAL BARRIL ',1,5617.32,10672.91,6,1);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (13,'IMPERIAL LATA ',1,90.25,171.48,277,1);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (14,'ISEN BARRIL ',1,3562.55,6768.85,0,1);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (15,'KUNSTMAN ',1,179.48,341.01,55,1);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (16,'MILLER BARRIL ',1,4100.66,7791.25,0,1);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (17,'MILLER LATA ',1,95.00,180.50,123,1);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (18,'MILLER PORRON ',1,99.75,189.53,0,1);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (19,'OM BEASTIE ALE ',1,43.35,82.37,0,1);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (20,'OM GOLDEN ',1,73.70,140.03,0,1);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (21,'OM INDIA PALE ALE ',1,51.92,98.65,0,1);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (22,'OM LAGER ',1,73.70,140.03,0,1);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (23,'OM NUT ',1,73.70,140.03,0,1);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (24,'OM RED ',1,73.70,140.03,0,1);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (25,'SCHNEIDER BARRIL ',1,705.50,1340.45,0,1);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (26,'SOL LATA ',1,130.53,248.01,41,1);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (27,'TUBO CO2 ',1,2066.12,3925.63,2,1);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (28,'WARSTEINER BARRIL ',1,7700.22,14630.42,4,1);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (29,'WARSTEINER LATA ',1,78.59,149.32,0,1);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (30,'WARSTEINER PORRON ',1,78.64,149.42,0,1);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (31,'ABSOLUT AZUL ',3,822.31,1562.39,65,1);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (32,'ABSOLUT CITRON ',3,672.52,1277.79,1,1);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (33,'ABSOLUT ELYX ',3,300.75,571.43,1,1);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (34,'ABSOLUT MANDARIN ',3,430.79,818.50,3,1);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (35,'ABSOLUT MANGO ',3,309.92,588.85,6,1);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (36,'ABSOLUT PEARS ',3,225.56,428.56,17,1);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (37,'ABSOLUT RASBERRY ',3,430.79,818.50,24,1);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (38,'AMARETTO LUXARDO ',3,221.80,421.42,0,1);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (39,'AMARETTO ',3,39.15,74.39,9,1);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (40,'AMARULA ',3,3097.94,5886.09,8,1);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (41,'ANTICA  FORMULA ',3,119.83,227.68,0,1);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (42,'APEROL ',3,578.51,1099.17,165,1);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (43,'BACARDI 8 ANOS ',3,99.51,189.07,0,1);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (44,'BACARDI BLANCO ',3,288.04,547.28,0,1);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (45,'BACARDI ORO ',3,288.04,547.28,0,1);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (46,'BAILEYS ',3,1163.54,2210.73,30,1);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (47,'BALLANTINES',3,169.22,321.52,37,1);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (48,'BEEFEATER ',3,800.00,1520.00,0,1);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (49,'BITTER ANG. ',3,3116.44,5921.24,0,1);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (50,'BITTER FEE. ',3,639.20,1214.48,0,1);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (51,'BITTER FEE. ORANGE ',3,639.20,1214.48,0,1);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (52,'BLUE CURACAO ',3,71.28,135.43,22,1);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (53,'BOMBAY ',3,2272.52,4317.79,0,1);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (54,'CACHACA ',3,268.00,509.20,52,1);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (55,'CACHACA VELHO ',3,625.21,1187.90,13,1);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (56,'CAMPARI ',3,578.51,1099.17,52,1);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (59,'CARPANO ROSSO ',3,268.47,510.09,24,1);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (60,'CASSIS LICOR ',3,319.63,607.30,8,1);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (61,'CHIVAS ',3,15552.89,29550.49,6,1);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (62,'CHIVAS ROYAL ',3,620.34,1178.65,2,1);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (63,'CINZANO ',3,45.67,86.77,0,1);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (64,'COINTREAU ',3,3182.23,6046.24,14,1);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (65,'CUERVO BLANCO ',3,1026.45,1950.26,0,1);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (66,'CUERVO ESPECIAL ',3,186.44,354.24,56,1);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (67,'CYNAR ',3,60.89,115.69,0,1);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (68,'DRAMBUIE ',3,3211.00,6100.90,3,1);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (69,'DURAZNO LICOR ',3,273.96,520.52,23,1);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (70,'FAMOUS GROUSE ',3,288.01,547.22,0,1);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (71,'FERNET BRANCA MENTA ',3,90.55,172.05,41,1);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (72,'FERNET BRANCA ',3,651.93,1238.67,49,1);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (73,'FERNET RAMAZOTTI ',3,48.52,92.19,0,1);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (74,'FLOR DE C. BLANCO ',3,446.00,847.40,22,1);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (75,'FLOR DE C. CENTENARIO ',3,294.62,559.78,6,1);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (76,'FRUTILLA LICOR ',3,319.63,607.30,24,1);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (77,'GANCIA ',3,225.54,428.53,38,1);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (78,'GIN MOHON ',3,206.76,392.84,0,1);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (79,'GLENDFIDDICH ',3,6568.18,12479.54,1,1);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (80,'GLENLIVET ',3,3786.18,7193.74,1,1);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (81,'GORDON S ',3,637.29,1210.85,0,1);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (82,'GRAND MARNIER ',3,2704.55,5138.65,1,1);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (84,'GRAPA ',3,634.34,1205.25,1,1);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (85,'GREY GOOSE ',3,4616.70,8771.73,1,1);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (86,'HAVANA CLUB 7 A ',3,965.91,1835.23,0,1);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (87,'HAVANA CLUB ',3,120.12,228.23,15,1);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (88,'HAVANA CLUB ORO ',3,51.78,98.38,0,1);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (89,'HENDRICK ',3,1721.07,3270.03,0,1);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (90,'HENNESSY RICHARD ',3,351.88,668.57,0,1);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (91,'HENNESSY VS ',3,351.88,668.57,0,1);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (92,'HENNESSY VSOP ',3,1417.11,2692.51,0,1);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (93,'HENNESSY XO ',3,351.88,668.57,0,1);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (94,'JB ',3,1011.53,1921.91,16,1);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (95,'J. W. BLACK ',3,2239.63,4255.30,4,1);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (96,'J. W. BLUE ',3,12817.40,24353.06,0,1);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (97,'J. W. RED ',3,143.69,273.01,2,1);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (98,'JACK DANIELS ',3,1457.59,2769.42,11,1);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (99,'JAMESON ',3,2519.56,4787.16,5,1);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (100,'JANGERMEISTER ',3,1868.60,3550.34,4,1);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (101,'JIM BEAM ',3,2057.32,3908.91,0,1);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (102,'JURA PROPHECY ',3,263.16,500.00,0,1);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (103,'KALUA ',3,319.63,607.30,3,1);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (104,'KIWI LICOR ',3,80.99,153.88,15,1);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (105,'LIMON LICORES STREGA ',3,2079.34,3950.75,33,1);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (106,'MALIBU ',3,541.32,1028.51,0,1);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (107,'MANZANA LICOR ',3,52.20,99.18,0,1);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (108,'MARTINI BIANCO ',3,37.84,71.90,32,1);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (109,'MARTINI DRY ',3,134.76,256.04,3,1);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (110,'MARTINI ROSSO ',3,157.79,299.80,50,1);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (111,'MELON LICOR ',3,319.63,607.30,35,1);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (112,'MENTA LICOR ',3,39.15,74.39,7,1);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (113,'NORDES GIN ',3,766.45,1456.26,0,1);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (114,'OPORTO FERREIRA ',3,54.87,104.25,2,1);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (115,'PISCO ',3,2002.06,3803.91,12,1);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (116,'PRAVDA VODKA ',3,400.30,760.57,0,1);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (117,'PUNT E MES ',3,77.07,146.43,50,1);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (118,'RESERVA SAN JUAN COGNAC',3,470.66,894.25,5,1);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (119,'SAMBUCA ',3,2181.05,4144.00,6,1);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (120,'SKYY ',3,578.50,1099.15,236,1);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (121,'SMIRNOFF CITRIC ',3,347.47,660.19,21,1);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (122,'SMIRNOFF ',3,651.83,1238.48,30,1);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (123,'SOUTHERN CONFORT ',3,47.09,89.47,0,1);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (124,'STREGA ',3,101.39,192.64,0,1);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (125,'TANQUERAY ',3,1435.45,2727.36,0,1);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (126,'TEQUILA HERENCIA ',3,264.37,502.30,6,1);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (127,'THE DALMORE 18 ANOS',3,220.63,419.20,0,1);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (128,'TIA MARIA ',3,63.91,121.43,5,1);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (129,'TRIPLE SEC ',3,456.61,867.56,49,1);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (130,'600cc COCA  ZERO ',2,51.65,98.14,0,2);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (131,'600cc COCA LIGHT ',2,51.65,98.14,0,2);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (132,'600cc COCA ',2,51.65,98.14,0,2);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (133,'600cc SPRITE ',2,39.38,74.82,0,2);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (134,'600cc SPRITE SA ',2,40.79,77.50,0,2);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (135,'600cc TONICA ',2,1.13,2.15,0,2);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (136,'ACEITUNAS VERDES ',2,225.77,428.96,0,2);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (137,'AGUA CON GAS ',2,35.91,68.23,1524,2);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (138,'AGUA SIN GAS ',2,35.91,68.23,1685,2);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (139,'ANANA RODAJAS ',2,453.87,862.35,18,2);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (140,'ARANDANOS CONGELADOS ',2,24.00,45.60,0,2);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (141,'CEBOLLITAS PERLA ',2,505.39,960.24,0,2);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (142,'CEREZA ',2,2752.46,5229.67,0,2);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (143,'COCA COLA 0 LATA ',2,59.68,113.39,17,2);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (144,'COCA COLA LATA ',2,59.69,113.41,2,2);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (145,'COCA COLA LIGHT LATA ',2,59.68,113.39,44,2);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (146,'COCA COLA LIGHT ',2,37.19,70.66,1175,2);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (147,'COCA COLA ',2,37.19,70.66,900,2);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (148,'COCA COLA ZERO ',2,37.19,70.66,928,2);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (151,'DURAZNOS EN ALMIBAR ',2,232.36,441.48,39,2);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (152,'EVIAN 750 ',2,151.35,287.57,0,2);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (153,'FANTA LATA ',2,40.47,76.89,0,2);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (154,'FANTA NARANJA ',2,37.19,70.66,186,2);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (156,'FRUTILLA CONGELADA ',2,449.67,854.37,36,2);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (157,'GRANADINA ',2,393.39,747.44,18,2);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (159,'JUGO DE TOMATE ',2,208.00,395.20,106,2);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (163,'LEVITE MANZANA CERO ',2,37.76,71.74,67,2);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (164,'LEVITE MANZANA ',2,37.77,71.76,5,2);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (165,'LEVITE NARANJA CERO ',2,32.50,61.75,43,2);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (166,'LEVITE NARANJA ',2,37.77,71.76,108,2);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (167,'LEVITE POMELO CERO ',2,37.76,71.74,113,2);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (168,'LEVITE POMELO ',2,37.77,71.76,73,2);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (169,'LYCHEE ',2,27.75,52.73,0,2);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (170,'MARACUYA CONGELADO ',2,884.00,1679.60,16,2);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (171,'OREO ',2,78.81,149.74,0,2);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (172,'SCHW TONICA BOT ',2,140.62,267.18,0,2);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (173,'SCHWE POMELO LATA ',2,43.00,81.70,0,2);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (174,'SCHWE TONICA LATA ',2,33.98,64.56,0,2);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (175,'SCHWEPES POMELO ',2,36.93,70.17,291,2);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (176,'SPRITE 0 LATA ',2,59.27,112.61,5,2);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (177,'SPRITE LATA ',2,59.27,112.61,0,2);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (178,'SPRITE LIGHT LATA ',2,37.46,71.17,0,2);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (179,'SPRITE ',2,36.93,70.17,375,2);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (181,'SPRITE ZERO ',2,36.93,70.17,513,2);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (182,'TONICA ',2,37.19,70.66,406,2);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (183,'WE CITRUS ',2,16.16,30.70,0,2);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (185,'AIME MOSCATEL ',4,251.89,478.59,22,2);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (186,'ALAMBRADO CHARDONAY ',4,100.01,190.02,0,2);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (187,'ALAMBRADO ESPUMANTE ',4,151.00,286.90,0,2);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (188,'ALAMBRADO MALBEC ',4,100.00,190.00,0,2);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (189,'ALAMOS CABERNET ',4,19.98,37.96,3,2);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (190,'ALAMOS CHARDONNAY ',4,395.04,750.58,55,2);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (191,'ALAMOS MALBEC ',4,259.27,492.61,0,2);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (192,'ALAMOS MOSCATEL ',4,136.00,258.40,0,2);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (193,'ALAMOS ROSADO ',4,50.00,95.00,0,2);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (194,'ALARIS MALBEC ',4,12.62,23.98,0,2);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (195,'ALMA MORA CH ',4,12.62,23.98,0,2);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (196,'ALMA MORA MALBEC ',4,12.62,23.98,0,2);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (197,'ALTA V. CAB. FRANC ',4,190.67,362.27,0,2);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (198,'ALTA V. CABERNET ',4,203.33,386.33,34,2);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (199,'ALTA V. CHARDONNAY ',4,209.74,398.51,52,2);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (200,'ALTA V. MALBEC 375cc ',4,2885.69,5482.81,0,2);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (201,'ALTA V. MALBEC ',4,203.33,386.33,46,2);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (202,'ANG. ZAPATA CABERNET ',4,1133.88,2154.37,2,2);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (203,'ANG. ZAPATA MALBEC ',4,2046.28,3887.93,13,2);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (204,'ARUMA MAL ',4,847.08,1609.45,40,2);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (205,'BARON B XB ',4,1169.45,2221.96,143,2);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (206,'BENJAMIN TARDIO ',4,129.80,246.62,0,2);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (207,'CABALLERO BLEND ',4,216.94,412.19,0,2);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (208,'CABALLERO CABERNET ',4,57.61,109.46,0,2);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (209,'CABALLERO CHARDONNAY ',4,57.61,109.46,0,2);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (210,'CABALLERO MALBEC ',4,57.61,109.46,6,2);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (211,'CADUS BLEND ',4,1385.56,2632.56,9,2);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (213,'CHANDON APERITIF ',4,392.73,746.19,84,2);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (214,'CHANDON XB ',4,392.73,746.19,89,2);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (215,'DEDICADO ',4,307.21,583.70,0,2);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (217,'DV CATENA ',4,1272.73,2418.19,34,2);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (218,'EL ESTECO ',4,495.83,942.08,3,2);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (219,'EMILIA NS MOSCATEL ',4,115.28,219.03,0,2);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (220,'FELIPE RUTTINI ',4,66.39,126.14,5,2);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (221,'FINCA NOTABLES ',4,786.74,1494.81,0,2);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (222,'FOND C. CABERNET ',4,235.76,447.94,236,2);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (223,'FOND C. CHARDONNAY ',4,235.73,447.89,0,2);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (224,'FOND C. GRAN RESERVA ',4,263.13,499.95,2,2);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (225,'FOND C. RVA MALBEC ',4,324.15,615.89,48,2);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (226,'FRAN BLEND ',4,79.77,151.56,0,2);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (227,'FRAN CHARDONNAY ',4,79.77,151.56,0,2);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (228,'FRAN MALBEC ',4,79.77,151.56,0,2);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (229,'GALA 3 ',4,537.19,1020.66,0,2);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (230,'GALA 4 ',4,126.67,240.67,1,2);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (231,'KANSAS MALBEC ',4,85.00,161.50,0,2);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (232,'KINIEN ',4,952.32,1809.41,6,2);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (233,'LA LINDA CABERNET ',4,20.61,39.16,0,2);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (234,'LA LINDA CHARDONNAY ',4,29.22,55.52,0,2);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (235,'LA LINDA MALBEC ',4,462.81,879.34,157,2);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (236,'LA LINDA XB ',4,504.13,957.85,56,2);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (237,'LOS ZUCCARDI Q ',4,1106.00,2101.40,7,2);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (238,'LUCA BESO DE DANTE ',4,1504.17,2857.92,5,2);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (239,'LUIGI BOSCA BOHEMME ',4,520.69,989.31,0,2);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (240,'LUIGI BOSCA BRUT NATURE ',4,211.58,402.00,0,2);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (241,'LUIGI BOSCA MALBEC ',4,814.05,1546.70,35,2);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (242,'LUIGI BOSCA SANGRE CAB ',4,1074.38,2041.32,10,2);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (243,'LUIGI BOSCA SANGRE WB ',4,18.59,35.32,0,2);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (244,'MEDALLA MALBEC ',4,22.93,43.57,1,2);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (245,'MORA NEGRA MALBEC ',4,46.63,88.60,0,2);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (246,'NAVARRO C. MALBEC 375cc ',4,2885.69,5482.81,28,2);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (247,'NAVARRO C. MALBEC ',4,240.72,457.37,52,2);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (248,'NAVARRO C. RVA. CHARD. ',4,214.50,407.55,37,2);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (249,'NAVARRO C. SAUV. BLANC ',4,84.99,161.48,0,2);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (250,'NAVARRO C. SYRAH ',4,240.68,457.29,1,2);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (251,'NAVARRO C. XB ',4,308.87,586.85,142,2);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (252,'NAVARRO C.RVA. MALBEC ',4,348.01,661.22,0,2);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (253,'NICASIA BLANC DB ',4,527.27,1001.81,21,2);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (254,'NICASIA BLEND MAL ',4,527.27,1001.81,19,2);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (255,'NICASIA CAB FRANC ',4,330.91,628.73,90,2);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (256,'NICOLAS CATENA ZAPATA ',4,3909.09,7427.27,2,2);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (257,'NIETO BLEND BLANCO ',4,22.13,42.05,1,2);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (258,'NIETO BLEND TINTO ',4,132.80,252.32,2,2);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (259,'NIETO BRUT NATURE ',4,367.29,697.85,0,2);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (260,'NIETO BRUT ROSE ',4,102.44,194.64,0,2);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (261,'NIETO CABERNET ',4,404.09,767.77,137,2);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (262,'NIETO CHARDONNAY ',4,368.87,700.85,83,2);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (263,'NIETO CT ',4,57.85,109.92,0,2);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (264,'NIETO GRAN CUVEE ',4,3.98,7.56,5,2);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (266,'NIETO MALBEC ',4,404.08,767.75,35,2);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (267,'NIETO MERLOT ',4,387.72,736.67,73,2);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (268,'NIETO XB ',4,457.58,869.40,52,2);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (269,'NOBLES C BOUCHET ',4,1342.97,2551.64,0,2);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (271,'NOBLES MALBEC V. ',4,90.91,172.73,3,2);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (272,'PETIT CARO ',4,1260.33,2394.63,8,2);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (273,'POSTA PINOT N ',4,735.50,1397.45,32,2);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (274,'POSTA PIZZELLA 20 ',4,735.50,1397.45,161,2);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (275,'RUCA MALEN BLEND ',4,13.72,26.07,86,2);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (276,'RUCA MALEN XB ',4,91.82,174.46,0,2);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (277,'RUCA RVA CABERNET ',4,521.33,990.53,119,2);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (278,'RUCA RVA CHARDONNAY ',4,123.16,234.00,6,2);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (279,'RUCA RVA MALBEC ',4,521.33,990.53,21,2);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (280,'RUTTINI CABERNET ',4,1012.17,1923.12,61,2);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (281,'RUTTINI GEWURZTAMINER ',4,1663.51,3160.67,5,2);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (282,'RUTTINI MALBEC ',4,1214.60,2307.74,36,2);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (283,'SAINT FELI. CAB. FRANC ',4,558.68,1061.49,126,2);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (284,'SAINT FELI. CAB. MERLOT ',4,77.00,146.30,0,2);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (285,'SAINT FELI. CABERNET ',4,586.61,1114.56,132,2);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (286,'SAINT FELI. CHARDONNAY ',4,604.96,1149.42,0,2);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (287,'SAINT FELI. FUME BLANC ',4,165.67,314.77,0,2);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (288,'SAINT FELI. MALBEC ',4,586.61,1114.56,71,2);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (289,'SINGLE VINEYARD ',4,716.42,1361.20,12,2);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (290,'STA. JULIA CABERNET',4,155.00,294.50,34,2);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (291,'STA. JULIA MERLOT ',4,155.00,294.50,29,2);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (292,'STA. JULIA SAUV. BLANC ',4,232.50,441.75,173,2);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (293,'STA. JULIA VIOGNIER ',4,155.00,294.50,17,2);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (294,'TENSION CABERNET ',4,102.45,194.66,0,2);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (295,'TENSION CHARDONNAY ',4,102.45,194.66,0,2);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (296,'TENSION MALBEC ',4,102.45,194.66,0,2);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (297,'TERRAZAS APELAC. ',4,223.08,423.85,0,2);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (298,'TERRAZAS CAV SAUV ',4,513.17,975.02,42,2);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (299,'TERRAZAS RVA MAL ',4,584.73,1110.99,118,2);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (301,'TRAPICHE DULCE ',4,125.23,237.94,0,2);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (302,'TRAPICHE MALBEC ',4,125.38,238.22,68,2);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (303,'TRAPICHE PINOT ',4,125.37,238.20,0,2);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (304,'TRUMPETER ROSADO ',4,722.98,1373.66,141,2);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (305,'TRUMPETER RVA BONARDA ',4,531.07,1009.03,0,2);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (306,'TRUMPETER RVA CABERNET ',4,722.98,1373.66,80,2);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (307,'TRUMPETER RVA MALBEC ',4,244.12,463.83,0,2);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (308,'TRUMPETER RVA PINOT ',4,420.40,798.76,0,2);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (309,'VEUVE CQUOT ',4,8086.85,15365.02,5,2);
INSERT INTO `` (`ID_Producto`,`Nombre_Producto`,`ID_Proveedor`,`Precio_Unitario`,`Precio_Venta`,`Stock`,`ID_Deposito`) VALUES (310,'ZAFFIRO ',4,166.98,317.26,127,2);
